# Generated by Django 3.2.9 on 2021-12-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addressee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rName', models.CharField(max_length=20)),
                ('rPhone', models.CharField(default='', max_length=50, null=True)),
                ('rAddr', models.CharField(default='', max_length=100, null=True)),
                ('rEmail', models.EmailField(default='', max_length=50, null=True)),
                ('rPay', models.CharField(default='', max_length=100, null=True)),
                ('rGrandtotal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rProduct', models.CharField(default='', max_length=100)),
                ('rPrice', models.IntegerField(default=0)),
                ('rQty', models.IntegerField(default=0)),
                ('rTotal', models.IntegerField(default=0)),
                ('rOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addressee')),
            ],
        ),
    ]
