# Generated by Django 3.2.9 on 2022-01-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_addressee_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressee',
            name='rAccount',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
