# Generated by Django 3.2.9 on 2022-01-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='cAccount',
            new_name='sAccount',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cAddr',
            new_name='sAddr',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cBirthday',
            new_name='sBirthday',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cEmail',
            new_name='sEmail',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cName',
            new_name='sName',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cPhone',
            new_name='sPhone',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cPswd',
            new_name='sPswd',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cSex',
            new_name='sSex',
        ),
    ]
