# Generated by Django 3.2.9 on 2022-01-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220105_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressee',
            name='rState',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
