# Generated by Django 3.2.9 on 2022-01-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_addressee_rstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pQty',
            field=models.IntegerField(default=0),
        ),
    ]
