# Generated by Django 3.2.9 on 2022-01-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_pqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pImage',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
