# Generated by Django 3.2.9 on 2022-01-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pImage',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
