# Generated by Django 3.2.9 on 2022-01-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pImage',
            new_name='pro_Image',
        ),
    ]
